Weiver-project/Weiver

.gitignore

[init]: 프론트엔드 작업 폴더 생성

---

front-end/css/login.css
front-end/css/public.css
front-end/html/clause.html

---
---
- firebase어쩌고
- 구글 어쩌고

[Feat]: 약관 페이지

---

front-end/css/inquiry.css
front-end/css/inquiryDetail.css
front-end/css/passwordUpdate.css
front-end/css/profileUpdate.css
front-end/css/setting.css
front-end/html/inquiry.html
front-end/html/inquiryDetail.html
front-end/html/mypage.html
front-end/html/passwordUpdate.html
front-end/html/profileUpdate.html
front-end/html/setting.html

#49 프로필 수정
#51 설정
#52 문의 메인
#53 비밀번호 변경
#56 문의사항 상세

[Design]: 마이페이지 #49 #51 #52 #53 #56

---

front-end/css/mypage.css
front-end/css/profileUpdate.css
front-end/html/profileUpdate.html

[Refacter] 프로필수정 페이지, 사진 변경 버튼 클릭 시 img파일만 받아올 수 있도록 수정 #49

---

front-end/css/communityDetailChat.css
front-end/html/communityDetailChat.html

[Design] 커뮤니티 잡담 디테일 페이지 퍼블리싱

---

front-end/css/communityDetailReview.css
front-end/html/communityDetailReview.html

#29
[Design] 커뮤니티 리뷰 상세페이지 퍼블리싱
#33
[Refactor] 커뮤니티 잡담 페이지 누락된 수정하기, 삭제하기 버튼 추가

[Design] 커뮤니티 리뷰 상세페이지 퍼블리싱

---

css/mainpage.css
html/mainpage.html
js/mainpage.js

#18
---
---
- firebase어쩌고
- 구글 어쩌고

[Design] 메인 페이지 퍼블리싱

---

css/musicalDetail.css
html/musicaldetail.html
js/musicalDetail.js

#41
---
---
- firebase어쩌고
- 구글 어쩌고

[Design] 뮤지컬 상세 페이지 퍼블리싱

---

front-end/css/mainpage.css
front-end/css/musicalDetail.css
front-end/html/mainpage.html
front-end/html/musicaldetail.html

---
name: 메인 페이지 네비게이션 바
---
네비게이션 바가 화면 아래로 내려가 가려지는 현상이 발생하여 이를 개선하기 위해 수정
z-index를 통해 네비게이션 바를 앞으로 가져옴.
- firebase어쩌고
- 구글 어쩌고
정상 출력 확인.

[Refacter] 메인 페이지 네비게이션 바가 제일 앞에 노출되도록 수정 #18

---

front-end/css/mainpage.css

---
name: 메인 페이지 코너 간 간격 수정
---
코너 간 간격이 맞지 않아 이를 통일하고자 간격 수정
margin-bottom 을 통한 간격 수정 
- firebase어쩌고
- 구글 어쩌고
정상적으로 출력됨.

[Refacter] 메인 페이지 코너 간 간격 수정 #18

---

front-end/css/actorDetail.css
front-end/css/myBoard.css
front-end/css/posting.css
front-end/html/actorDetail.html
front-end/html/inquiryForm.html
front-end/html/myBoard.html
front-end/html/myComment.html
front-end/html/myLike.html
front-end/html/posting.html

---
---
- firebase어쩌고
- 구글 어쩌고

[Design] 글 작성 페이지

---

front-end/css/inquiry.css
front-end/css/inquiryDetail.css
front-end/css/mypage.css
front-end/css/passwordUpdate.css
front-end/css/profileUpdate.css
front-end/css/setting.css
front-end/html/communitty.html

[Refactor]: 마이페이지 네비, 푸터, 헤더 위치 수정 #48 #49 #51 #52 #53 #56

---

front-end/css/mainpage.css
front-end/css/musicalDetail.css
front-end/html/mainpage.html
front-end/html/musicaldetail.html

---
name: [Refactor] 메인 페이지 오늘의 배우 스와이프 기능 수정 #18
---
배우 작품에 대한 스와이프가 제대로 작동하지 않아 수정할 필요가 있음.
- firebase어쩌고
- 구글 어쩌고
테스트 시 정상 작동 확인.

[Refactor] 메인 페이지 오늘의 배우 스와이프 기능 수정 #18

---

front-end/css/mainpage.css
front-end/css/musicalDetail.css
front-end/css/public.css
front-end/html/mainpage.html
front-end/html/musicaldetail.html

---
---
public css 통일하여 수정
- firebase어쩌고
테스트하여 정상 작동 확인 완료.

[Refactor] public css 수정

---

back-end/Weiver/pom.xml
back-end/Weiver/src/main/java/controller/MusicalController.java
back-end/Weiver/src/main/java/dto/MusicalDTO.java
back-end/Weiver/src/main/java/service/MusicalService.java
back-end/Weiver/src/main/resources/application.properties

---
---
- firebase어쩌고
- 구글 어쩌고

[Chore]: dependency 추가, properties 파일 작성, 기본 폴더 추가

---

front-end/css/inquiry.css
front-end/css/inquiryDetail.css
front-end/css/mypage.css
front-end/css/passwordUpdate.css
front-end/css/profileUpdate.css
front-end/css/setting.css
front-end/html/inquiry.html
front-end/html/inquiryDetail.html
front-end/html/mypage.html
front-end/html/passwordUpdate.html
front-end/html/profileUpdate.html
front-end/html/setting.html

[Refactor]: 마이페이지 public.css 적용 #48 #49 #51 #52 #53 #56

---

.gitignore
back-end/Weiver/.gitignore
back-end/data-sever/.gitignore

[Chore] gitignore 업데이트

---

back-end/Weiver/src/main/resources/static/css/actor.css
back-end/Weiver/src/main/resources/static/css/community.css
back-end/Weiver/src/main/resources/static/css/inquiry.css
back-end/Weiver/src/main/resources/static/css/login.css
back-end/Weiver/src/main/resources/static/css/musical.css
back-end/Weiver/src/main/resources/static/css/posting.css
back-end/Weiver/src/main/resources/static/css/public.css
back-end/Weiver/src/main/resources/static/css/searchAll.css
back-end/Weiver/src/main/resources/static/css/swiper.css
back-end/Weiver/src/main/resources/static/css/user.css
back-end/Weiver/src/main/webapp/WEB-INF/views/community.jsp

---
name: [FEAT] 백엔드 파일에 CSS 경로 지정하여 추가, jsp 경로 지정
---
추가 완료. 정상적으로 작동될 것으로 예상되나 일부 수정이 필요할 수 있음.

[FEAT] 백엔드 파일에 CSS 경로 지정하여 추가, jsp 경로 지정

---

back-end/data-sever/pom.xml
back-end/data-sever/src/main/java/datasever/DataSeverApplication.java
back-end/data-sever/src/main/java/datasever/kopis/KopisService.java
back-end/data-sever/src/main/java/datasever/repository/MusicalRepository.java
back-end/data-sever/src/main/java/entity/Musical.java
back-end/data-sever/src/main/resources/application.properties

[Feat]: 뮤지컬 목록 API로 뮤지컬 아이디 리스트 가져오기

---

back-end/Weiver/src/main/java/weiver/config/MongoDBConfig.java
back-end/Weiver/src/main/java/weiver/controller/MusicalController.java
back-end/Weiver/src/main/java/weiver/controller/UserController.java
back-end/Weiver/src/main/java/weiver/dto/MusicalDTO.java
back-end/Weiver/src/main/java/weiver/dto/User.java
back-end/Weiver/src/main/java/weiver/repository/UserRepository.java
back-end/Weiver/src/main/java/weiver/service/MusicalService.java
back-end/Weiver/src/main/java/weiver/service/UserService.java
back-end/Weiver/src/main/resources/application.properties

---
---
- firebase어쩌고
- 구글 어쩌고

[Feat]: User 정보 조회, 수정

---

back-end/Weiver/src/main/java/weiver/controller/UserController.java
back-end/Weiver/src/main/java/weiver/dto/User.java
back-end/Weiver/src/main/java/weiver/repository/UserRepository.java
back-end/Weiver/src/main/java/weiver/service/UserService.java

---
---
- firebase어쩌고
- 구글 어쩌고

[Refactor]: 유저 정보 수정 기능 #34

---

back-end/Weiver/pom.xml
back-end/Weiver/src/main/resources/application.properties

---
---
- firebase어쩌고
- 구글 어쩌고

[Feat] pom.xml, properties 파일 오라클 세팅 정보 추가

---

front-end/css/public.css
front-end/html/mainpage.html
front-end/html/myComment.html

---
---
강사님 피드백에 따라 nav 바에 패딩 주었음.
정상 동작 확인 완료.

[Refactor] 프론트엔드 css 파일 수정

---

back-end/Weiver/pom.xml
back-end/Weiver/src/main/java/weiver/controller/LoginController.java
back-end/Weiver/src/main/java/weiver/service/LoginService.java
back-end/Weiver/src/main/resources/application.properties
front-end/html/login.html

[Test] 로그인 기능 개발중 

---

ddl.txt

---
---
- firebase어쩌고
- 구글 어쩌고

[refactor] ddl

---

back-end/Weiver/src/test/testdata.txt

---
---
user, post 테스트 데이터 삽입 위한 sql문 담긴 txt 파일
sql developer에 작동했을 때 정상적으로 데이터 삽입 완료됨.

[Feat] 테스트 데이터 삽입

---

front-end/css/signup.css
front-end/html/signup.html

signup 페이지 html, css, js(모달창) 완료

[design] 회원가입 페이지 html, css, js(모달창)

---

ddl.txt

---
---
이용약관 추가
- firebase어쩌고
- 구글 어쩌고

[Refactor] ddl 수정

---

back-end/Weiver/src/main/java/weiver/controller/LoginController.java
back-end/Weiver/src/main/webapp/WEB-INF/views/signup.jsp
front-end/css/signup.css

[Fix] 로그인 컨트롤러 예외 제거

---

back-end/Weiver/src/test/testdata.txt

---
---
db 수정에 따른 테스트 데이터 수정
sql developer에 넣었을 때 정상적으로 작동되는 것을 확인.

[Refactor] 테스트 데이터 (user_tb, post)

---

back-end/Weiver/src/main/java/weiver/entity/Image.java
back-end/Weiver/src/main/java/weiver/entity/Post.java
back-end/Weiver/src/main/java/weiver/entity/PostLike.java
back-end/Weiver/src/main/java/weiver/repository/CommunityRepository.java

---
---
커뮤니티 CRUD 관련 entity, repository 작업
repository 중 주석 처리한 부분만 제외하면 모두 정상작동.

[Feat] 커뮤니티 관련 entity, repository

---

back-end/Weiver/src/test/testdata.txt

---
---
테스트 데이터 추가 (>> 23.07.12 새로 생성 <<) 참조
정상적으로 데이터 삽입되는 것 확인함.

[Refactor] 테스트 데이터 추가

---

back-end/Weiver/src/main/java/weiver/entity/Post.java
back-end/Weiver/src/main/java/weiver/entity/ReReply.java
back-end/Weiver/src/main/java/weiver/entity/ReReplyLike.java
back-end/Weiver/src/main/java/weiver/entity/Reply.java
back-end/Weiver/src/main/java/weiver/entity/ReplyLike.java

---
title: 'Pull request from m1n1_boo/Weiver to Weiver-project/Weiver'
---
entity 생성 후 참조 관계 형성
정상적으로 데이터 받아오는 것 확인함. (수정된 db 기반으로 작성됨.)

[Feat] entity 생성 후 참조 (post, reply, reply_like, re_reply, re_reply_like)

---

back-end/data-sever/src/main/java/datasever/DataSeverApplication.java
back-end/data-sever/src/main/java/datasever/kopis/KopisService.java
back-end/data-sever/src/main/java/datasever/kopis/PlayDBService.java
back-end/data-sever/src/main/java/datasever/repository/ActorRepository.java
back-end/data-sever/src/main/java/model/ActorTest.java

---
---
- firebase어쩌고
- 구글 어쩌고

[Refacter]: 뮤지컬 정보 저장 로직 변경

---

back-end/Weiver/src/main/java/weiver/controller/CommunityController.java
back-end/Weiver/src/main/java/weiver/entity/Post.java
back-end/Weiver/src/main/java/weiver/repository/CommunityRepository.java
back-end/Weiver/src/main/java/weiver/repository/ReReplyRepository.java
back-end/Weiver/src/main/java/weiver/repository/ReplyRepository.java
back-end/Weiver/src/main/java/weiver/repository/UserRepository.java
back-end/Weiver/src/main/java/weiver/service/CommunityService.java

---
title: 'Pull request from m1n1-boo/Weiver to Weiver-project/Weiver'
---
커뮤니티 관련 전반적인 기능 구현을 위한 조회/수정/삭제 메소드 구현
TEST시 정상적으로 작동 확인 됨.

[Feat] 커뮤니티 게시글, 댓글, 대댓글 조회/수정/삭제 백엔드 관련 구현

---

.gitignore
back-end/data-sever/src/main/java/com/example/DataSeverApplication.java
back-end/data-sever/src/main/java/com/example/entity/Actor.java
back-end/data-sever/src/main/java/com/example/entity/Casting.java
back-end/data-sever/src/main/java/com/example/entity/Musical.java
back-end/data-sever/src/main/java/com/example/repository/CastingRepository.java
back-end/data-sever/src/main/java/com/example/service/ActorService.java
dropTable.txt

Musical 데이터는 임시적으로 ActorService.java에서 만들어 넣었다.

[Feat] PlayDB에서 Oracle 기반 Actor, Casting 데이터 수집 

---

back-end/Weiver/src/main/java/weiver/controller/UserController.java
back-end/Weiver/src/main/java/weiver/repository/UserRepository.java
back-end/Weiver/src/main/java/weiver/service/UserService.java
back-end/Weiver/src/main/resources/static/css/login.css
back-end/Weiver/src/main/resources/static/css/user.css
back-end/Weiver/src/main/webapp/WEB-INF/views/passwordUpdate.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/profileUpdate.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/setting.jsp

---
---
- firebase어쩌고
- 구글 어쩌고

[Feat]: 설정 페이지 jsp #60 / [Feat]: 프로필 수정 페이지 #58 / [Feat]: 비밀번호 변경 페이지 #61

---

back-end/Weiver/src/main/java/weiver/controller/CommunityController.java
back-end/Weiver/src/main/resources/application.properties
back-end/Weiver/src/main/webapp/WEB-INF/views/communityDetail.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/updatePost.jsp

---
title: 'Pull request from m1n1-b00/Weiver to Weiver-project/Weiver'
---
게시글 수정에 대한 기능 구현
테스트 필요함. 오류 없음.

[Feat] 게시글 Update 관련 기능 구현

---

back-end/Weiver/src/main/java/weiver/repository/SubscribeRepository.java
back-end/Weiver/src/main/java/weiver/service/MusicalService.java
back-end/Weiver/src/main/java/weiver/service/SubscribeService.java
back-end/data-sever/src/main/java/com/example/service/MusicalService.java

---
---
- firebase어쩌고
- 구글 어쩌고

[fix] subscribe repository 쿼리 에러 해결

---

back-end/Weiver/src/main/java/weiver/controller/CommunityController.java
back-end/Weiver/src/main/java/weiver/repository/CommunityRepository.java
back-end/Weiver/src/main/java/weiver/repository/ImageRepository.java
back-end/Weiver/src/main/java/weiver/repository/ReReplyRepository.java
back-end/Weiver/src/main/java/weiver/repository/ReplyRepository.java
back-end/Weiver/src/main/java/weiver/service/CommunityService.java
back-end/Weiver/src/main/webapp/WEB-INF/views/communityDetail.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/communityMain.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/rereplyDetail.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/updatePost.jsp
front-end/html/posting.html

---
---
커뮤니티 기능 구현 관련
- firebase어쩌고
- 구글 어쩌고
오류 없음.

[feat] 커뮤니티 기능 구현 관련

---

back-end/Weiver/src/main/webapp/WEB-INF/views/registerPost.jsp

---
---
- firebase어쩌고
- 구글 어쩌고

[feat] 커뮤니티 글 작성 페이지 jsp

---

back-end/Weiver/src/main/java/weiver/controller/MusicalController.java
back-end/Weiver/src/main/java/weiver/dto/SimpleMusicalDTO.java
back-end/Weiver/src/main/java/weiver/repository/SubscribeRepository.java
back-end/Weiver/src/main/webapp/WEB-INF/views/main.jsp

---
---
- firebase어쩌고
- 구글 어쩌고

[refactor]: 스와이퍼 위치 오류 해결 및 구독 @Query 부분 누락된 as 절 추가

---

back-end/Weiver/src/main/java/weiver/controller/CommunityController.java
back-end/Weiver/src/main/java/weiver/entity/Image.java
back-end/Weiver/src/main/java/weiver/entity/Post.java
back-end/Weiver/src/main/java/weiver/service/CommunityService.java
back-end/Weiver/src/main/webapp/WEB-INF/views/registerPost.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/updatePost.jsp

[refactor] 커뮤니티 관련 기능

---

back-end/Weiver/src/main/webapp/WEB-INF/views/rereplyDetail.jsp

[refactor] jsp-replydetail 수정

---

back-end/Weiver/pom.xml
back-end/Weiver/src/main/java/weiver/controller/CommunityController.java
back-end/Weiver/src/main/java/weiver/entity/Post.java
back-end/Weiver/src/main/java/weiver/entity/PostLike.java
back-end/Weiver/src/main/java/weiver/repository/PostLikeRepository.java
back-end/Weiver/src/main/java/weiver/service/CommunityService.java
back-end/Weiver/src/main/java/weiver/service/UserService.java
back-end/Weiver/src/main/resources/static/css/community.css
back-end/Weiver/src/main/webapp/WEB-INF/views/communityDetail.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/communityMain.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/registerPost.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/updatePost.jsp

---
---
커뮤니티 관련 기능 수정 및 전반적인 디테일 잡기
찬영님 것 pull request받은 후에 제 수정된 코드 반영했어요.
정상적으로 작동하고 있음.

[Refactor] 기능 수정 및 전반적인 디테일 잡기

---

back-end/data-sever/src/main/java/com/example/service/MusicalService.java

---
---
- firebase어쩌고
- 구글 어쩌고

[Refactor]  data-server 불필요한 로직 제거 및 리팩토링

---

back-end/Weiver/src/main/java/weiver/controller/MusicalController.java
back-end/Weiver/src/main/java/weiver/dto/ResponseCastingDTO.java
back-end/Weiver/src/main/java/weiver/repository/CastingRepository.java
back-end/Weiver/src/main/java/weiver/repository/MusicalRepository.java
back-end/Weiver/src/main/java/weiver/service/ActorService.java
back-end/Weiver/src/main/webapp/WEB-INF/views/musicalDetail.jsp

[feature] 배우 기능 완료

---

back-end/Weiver/src/main/java/weiver/controller/UserController.java
back-end/Weiver/src/main/java/weiver/repository/CommunityRepository.java
back-end/Weiver/src/main/java/weiver/service/UserService.java

---
---
- firebase어쩌고
- 구글 어쩌고

[Refactor]: 게시글 조회 에러 주석

---

back-end/Weiver/src/main/java/weiver/controller/UserController.java
back-end/Weiver/src/main/java/weiver/dto/PostDTO.java
back-end/Weiver/src/main/java/weiver/repository/CommunityRepository.java
back-end/Weiver/src/main/java/weiver/repository/PostLikeRepository.java
back-end/Weiver/src/main/java/weiver/service/UserService.java
back-end/Weiver/src/main/webapp/WEB-INF/views/myBoard.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/myLike.jsp

---
---
- firebase어쩌고
- 구글 어쩌고

[Refactor]: 게시물 조회 에러 수정

---

back-end/Weiver/src/main/java/weiver/controller/MusicalController.java
back-end/Weiver/src/main/java/weiver/dto/ResponseCastingDTO.java
back-end/Weiver/src/main/java/weiver/repository/CastingRepository.java
back-end/Weiver/src/main/webapp/WEB-INF/views/musicalDetail.jsp

- 출연진 정보 스와이핑 수정 ( 한 번에 최대 6명 )
- 하이퍼링크 추가 ( 출연진 클릭시 ActorDetail로 이동 )
- 유튜브 클립 에러 메시지 해결

[Refactor] MusicalDetail 세부사항 수정

---

back-end/Weiver/src/main/java/weiver/controller/CommunityController.java
back-end/Weiver/src/main/java/weiver/service/MusicalService.java
back-end/data-sever/src/main/java/com/example/entity/Casting.java
back-end/data-sever/src/main/java/com/example/service/MusicalService.java

---
---
- firebase어쩌고
- 구글 어쩌고

캐스팅 시퀀스 및 게시글 작성 컨트롤러 수정

---

back-end/Weiver/src/main/webapp/WEB-INF/views/registerPost.jsp

---
---
리뷰 게시글 작성 시에 뮤지컬 데이터 받아와서 검색 창에 뿌려줄 수 있도록 수정
- firebase어쩌고
- 구글 어쩌고

[Refactor] 뮤지컬 데이터 받아올 수 있도록 관련 정보 수정

---

back-end/Weiver/src/main/webapp/WEB-INF/views/registerPost.jsp

[Refactor] 작품명 검색 관련 !문제 있음!

---

back-end/Weiver/src/main/java/weiver/controller/InquiryController.java
back-end/Weiver/src/main/java/weiver/controller/LoginController.java
back-end/Weiver/src/main/java/weiver/controller/LoginViewController.java
back-end/Weiver/src/main/java/weiver/controller/UserController.java
back-end/Weiver/src/main/java/weiver/entity/Inquiry.java
back-end/Weiver/src/main/java/weiver/service/InquiryService.java
back-end/Weiver/src/main/webapp/WEB-INF/views/actorDetail.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/communityDetail.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/communityMain.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/communitySearchResult.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/inquiry.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/inquiryDetail.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/inquiryForm.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/login.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/main.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/musicalDetail.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/musicalSearch.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/myBoard.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/myComment.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/myLike.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/mypage.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/passwordUpdate.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/profileUpdate.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/registerPost.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/rereplyDetail.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/setting.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/signup.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/updatePost.jsp

[refactor] 페이지 연결, 로그인 기능 수정

---

back-end/Weiver/src/main/java/weiver/controller/CommunityController.java
back-end/Weiver/src/main/webapp/WEB-INF/views/registerPost.jsp

---
---
- firebase어쩌고
- 구글 어쩌고

[feat] 실시간 뮤지컬 검색 기능 구현

---

back-end/Weiver/src/main/java/weiver/controller/LoginController.java
back-end/Weiver/src/main/java/weiver/controller/LoginViewController.java
back-end/Weiver/src/main/webapp/WEB-INF/views/musicalDetail.jsp

[fixed] 로그인 페이지 에러 수정

---

back-end/Weiver/src/main/java/weiver/controller/MusicalController.java
back-end/Weiver/src/main/webapp/WEB-INF/views/main.jsp

---
---
- firebase어쩌고
- 구글 어쩌고

[fix] : 인기게시글 없을 때 나는 에러 해결

---

back-end/Weiver/src/main/java/weiver/controller/CommunityController.java
back-end/Weiver/src/main/java/weiver/entity/Review.java
back-end/Weiver/src/main/java/weiver/repository/ReviewRepository.java
back-end/Weiver/src/main/java/weiver/service/CommunityService.java
back-end/Weiver/src/main/webapp/WEB-INF/views/communityDetail.jsp

---
---
- firebase어쩌고
- 구글 어쩌고

[fefactor] 커뮤니티 상세 페이지 뮤지컬 정보 뿌려주는 로직 구현

---

back-end/Weiver/src/main/java/weiver/controller/CommunityController.java
back-end/Weiver/src/main/java/weiver/controller/UserController.java
back-end/Weiver/src/main/java/weiver/service/LoginService.java
back-end/Weiver/src/main/java/weiver/service/UserService.java
back-end/Weiver/src/main/webapp/WEB-INF/views/musicalDetail.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/mySubscribe.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/mypage.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/registerPost.jsp
ddl.sql

---
---
- firebase어쩌고
- 구글 어쩌고

[Refactor]: 오류 수정

---

back-end/data-sever/pom.xml
back-end/data-sever/src/main/resources/application.properties

---
---
- firebase어쩌고
- 구글 어쩌고

[Feat]: orcle db url 수정 및 메이븐 빌드 시 테스트 생략 코드 pom.xml에 추가

---

back-end/data-sever/src/main/java/com/example/service/MusicalService.java
back-end/data-sever/src/main/resources/application.properties

---
---
- firebase어쩌고
- 구글 어쩌고

scott 계정이 권한이 없어서 user테이블스페이스 제한을 헤제할 수 없어 admin 계정으로 변경

---

back-end/Weiver/src/main/resources/static/css/inquiry.css
back-end/Weiver/src/main/webapp/WEB-INF/views/inquiryDetail.jsp

[Refactor]: 문의사항 게시글 줄바꿈 에러 수정

---

back-end/Weiver/src/main/java/weiver/controller/CommunityController.java
back-end/Weiver/src/main/java/weiver/service/CommunityService.java
back-end/Weiver/src/main/resources/static/css/community.css
back-end/Weiver/src/main/resources/static/css/posting.css
back-end/Weiver/src/main/webapp/WEB-INF/views/registerPost.jsp

---
title: 'Pull request from M1N1-boo/Weiver to Weiver-project/Weiver'
---
- firebase어쩌고
- 구글 어쩌고
정상 작동 확인 완료.

[Refactor] 리뷰 정보 저장 관련 수정

---

back-end/Weiver/src/main/java/weiver/controller/AdminController.java
back-end/Weiver/src/main/java/weiver/controller/CommunityController.java
back-end/Weiver/src/main/java/weiver/controller/UserController.java
back-end/Weiver/src/main/java/weiver/repository/AdminRepository.java
back-end/Weiver/src/main/java/weiver/service/AdminService.java
back-end/Weiver/src/main/java/weiver/service/LoginService.java
back-end/Weiver/src/main/webapp/WEB-INF/views/adminLogin.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/adminSignup.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/mypage.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/profileUpdate.jsp

---
---
- firebase어쩌고
- 구글 어쩌고

[Refactor]: 프로필 aws s3 적용

---

back-end/Weiver/src/main/java/weiver/controller/CommunityController.java
back-end/Weiver/src/main/java/weiver/entity/PostLike.java
back-end/Weiver/src/main/java/weiver/repository/PostLikeRepository.java
back-end/Weiver/src/main/java/weiver/service/CommunityService.java
back-end/Weiver/src/main/java/weiver/service/UserService.java
back-end/Weiver/src/main/resources/static/css/community.css
back-end/Weiver/src/main/resources/static/css/musical.css
back-end/Weiver/src/main/resources/static/css/posting.css
back-end/Weiver/src/main/resources/static/css/searchAll.css
back-end/Weiver/src/main/webapp/WEB-INF/views/communityDetail.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/communityMain.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/communitySearchResult.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/musicalDetail.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/musicalSearch.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/registerPost.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/rereplyDetail.jsp

---
---
유저 서비스 페이지 전반 작업
- 뮤지컬 상세 페이지 찜, 구독하기 버튼 수정
- 커뮤니티 디테일 페이지 좋아요
- 게시글 작성 시 엔터 수정
- 검색 결과 페이지 링크 연결
- 대댓글 url 수정
완료.

[Refactor] 전반적인 UI 기능 수정

---

back-end/Weiver/src/main/webapp/WEB-INF/views/registerPost.jsp

[Refactor] 커뮤니티 작성 수정

---

back-end/Weiver/src/main/webapp/WEB-INF/views/registerPost.jsp

[Refactor] 게시글 수정 (잠시 보류한 거 주석처리 함)

---

back-end/Weiver/src/main/webapp/WEB-INF/views/adminUsers.jsp

[Refactor]: 관리자 유저 삭제 기능 추가

---

back-end/Weiver/src/main/resources/static/css/posting.css
back-end/Weiver/src/main/webapp/WEB-INF/views/communityDetail.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/musicalDetail.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/registerPost.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/rereplyDetail.jsp

[Refactor] 코드 디테일 수정

---

back-end/Weiver/src/main/java/weiver/controller/LoginController.java
back-end/Weiver/src/main/java/weiver/repository/MusicalRepository.java
back-end/Weiver/src/main/webapp/WEB-INF/views/actorDetail.jsp

뮤지컬 검색 : 뮤지컬 조회 최신순으로 
배우 상세페이지 제목 추가

[fixed] 뮤지컬 조회 최신순, 배우 상세페이지 제목 추가

---

back-end/Weiver/src/main/webapp/WEB-INF/views/adminAdmins.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/adminLogin.jsp

- Admin 회원가입이 노출되어 있는 것이 좋지 않은 것 같아 주석 처리하였다.
- Admin-admin 로그아웃 버튼이 잘못 링크되어 있는 것을 개선하였다.

[Refactor] 관리자 페이지 (회원가입 기능 삭제, 로그아웃 페이지 이동 개선)

---

back-end/Weiver/src/main/webapp/WEB-INF/views/main.jsp
back-end/data-sever/src/main/java/com/example/service/MusicalService.java

---
---
- firebase어쩌고
- 구글 어쩌고

[Refactor] 데이터 서버 크롤링 시 날짜 글자 수 변경

---

back-end/Weiver/src/main/webapp/WEB-INF/views/registerPost.jsp

[Refactor] 뮤지컬 기한 표기되게 js 수정

---

back-end/Weiver/src/main/webapp/WEB-INF/views/mySubscribe.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/mypage.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/passwordUpdate.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/profileUpdate.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/setting.jsp

---
---
- firebase어쩌고
- 구글 어쩌고

[Refactor]: 마이페이지 url 수정

---

back-end/Weiver/src/main/resources/application.properties

---
---
- firebase어쩌고
- 구글 어쩌고

[refactor] kakao url 변경

---

back-end/Weiver/src/main/java/weiver/controller/AnswerController.java
back-end/Weiver/src/main/java/weiver/repository/ReplyRepository.java
back-end/Weiver/src/main/java/weiver/service/CommunityService.java

---
---
- firebase어쩌고
- 구글 어쩌고

[Refactor]: admin url 수정

---

back-end/Weiver/src/main/webapp/WEB-INF/views/communitySearchResult.jsp

[refator] 커뮤니티 검색 결과 페이지 이미지 수정
현수님 slack 메시지 11:06 메시지로 수정함

[refator] 커뮤니티 검색 결과 페이지 이미지 수정

---

back-end/Weiver/src/main/webapp/WEB-INF/views/communityDetail.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/communityMain.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/communitySearchResult.jsp

---
---
- firebase어쩌고
- 구글 어쩌고

[refator]  JSP 이미지 변수명 변경

---

back-end/Weiver/src/main/java/weiver/controller/CommunityController.java
back-end/Weiver/src/main/java/weiver/entity/Post.java
back-end/Weiver/src/main/java/weiver/service/CommunityService.java
back-end/Weiver/src/main/webapp/WEB-INF/views/communityMain.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/registerPost.jsp

---
---
- firebase어쩌고
- 구글 어쩌고

[refactor] 게시글 등록 수정

---

back-end/Weiver/src/main/java/weiver/service/KakaoService.java
back-end/Weiver/src/main/webapp/WEB-INF/views/communityMain.jsp

[fix] 커뮤니티 메인 페이지 위로가기 버튼 삭제, 스크립트 정리

[fix] 커뮤니티 메인 페이지 위로가기 버튼 삭제, 스크립트 정리

---

back-end/Weiver/src/main/java/weiver/controller/MusicalController.java
back-end/Weiver/src/main/webapp/WEB-INF/views/config.jsp

---
---
- firebase어쩌고
- 구글 어쩌고

[refactor] : 찜하기 로그인 이슈 해결

---

back-end/Weiver/src/main/webapp/WEB-INF/views/passwordUpdate.jsp
back-end/Weiver/src/main/webapp/WEB-INF/views/signup.jsp

[fixed] 비밀번호 최소 6자 ~ 20자

---

back-end/Weiver/src/main/java/weiver/controller/CommunityController.java
back-end/Weiver/src/main/java/weiver/repository/PostLikeRepository.java
back-end/Weiver/src/main/java/weiver/service/CommunityService.java
back-end/Weiver/src/main/webapp/WEB-INF/views/communityDetail.jsp

[fixed] 커뮤니티 상세 페이지 좋아요 유지 기능 수정!

[fixed] 커뮤니티 상세 페이지 좋아요 유지 기능 수정!

---

back-end/Weiver/src/main/java/weiver/repository/CommunityRepository.java
back-end/Weiver/src/main/resources/static/css/community.css

[fixed] 게시글 최신순 정렬, 커뮤니티 게시글 div 크기 조절

[fixed] 게시글 최신순 정렬, div 크기 조절
